### PR TITLE
Stateless Skylight Component

### LINKED ISSUE #32: Open-state should be exposed as prop
In Flux/Redux apps, the state of components is externalized and injected via properties. What I would like to do is have flux events that mutate the contents of the skylight, then present it by setting the "open" state to true.

### PR DESCRIPTION
**Pull request by darthtrevino**
Hey @marcio ,
This PR adds a new component: SkyLightStateless. This component externalizes it's open-state to a property. This allows it to be used in Flux/Redux contexts. 

I've also updated a couple of libs and did some boilerplatey cleanup. Let me know if you have any questions!

-Chris

Fixes #32

### CODE REVIEW

**Comment by marcio** [comment]
Hi @darthtrevino,

Looks good man! I will analyse and merge as soon as I can.
I need some time to write some documentation about that too.

Thanks.

**Comment by darthtrevino** [comment]
Awesome! If you have a good test-bed for the main Skylight component, it would be worthwhile to test that. I'm using the stateless component in an app I'm writing, but I haven't had a chance to dig too far into stateful one.

**Comment by darthtrevino** [comment]
@marcio I added some unit tests to verify that everything was still behaving correctly. You're welcome. ;-)

**Comment by marcio** [comment]
Wow!! Thanks @darthtrevino!! 
This week I'll work on merge and docs.If everything goes well I publish a new version. 👍

**Pull request merged**
